name: Reuters Scraper

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone 。+8才是北京时间，每天10点05分
    - cron: '05 2,14 * * *'
  watch:
    types: started

permissions:
  contents: write  # 授予 GITHUB_TOKEN 对内容的写入权限，则无需手动setting

jobs:
  scrape:
    runs-on: ubuntu-latest

    # 定时，或者自己点击star则运行此workflow
    if: github.event_name == 'schedule' || github.event_name == 'watch' && github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: |
          pip install -r requirements.txt

      - name: 运行爬虫
        run: python rt.py

      - name: 提交并推送更新
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add files/remote/news.json
          git commit -m "Update China news titles" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # github默认的
        continue-on-error: true  # 如果没有变化，跳过错误
