# github actions的yml配置文件
name: getNews
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone 。+8才是北京时间，每天10点05分
    - cron: '11 8 * * *'
  watch:
    types: started

permissions:
  contents: write  # 授予 GITHUB_TOKEN 对内容的写入权限，则无需手动setting

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium translate

    - name: Install Chromium and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        # 确保 ChromeDriver 在 PATH 中
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

    - name: Run scrape script
      run: python scrape_news.py

    - name: Commit and push results
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add file/china_news_titles.txt
        git commit -m "Update China news titles" || echo "No changes to commit"
        git push
      continue-on-error: true  # 如果没有变化，跳过错误

        # GitHub Actions 默认使用 actions/checkout@v3 时，会自动配置 GITHUB_TOKEN，可直接推送到同一仓库，无需额外 Token。但要确保：
        #GitHub Actions 运行在 main 分支（或你设定的分支）。
        #GitHub Actions 具有推送权限（默认对 main 分支可能是受限的，可检查仓库的 “Branch Protection Rules”）。
        #如果推送失败，可能需要 在 Settings -> Actions -> General 里启用 “Read and Write permissions”。




